Repository Epitech-R-Type/R-Type, pull requests merged in 2022-10, with the labels that each got.

#11 [Style] add linter workflow
  .clang-format
  .github/workflows/build_windows.yml
  .github/workflows/linter.yml
Labels: CI / Testing, Other

#15 [Feature] ECS & basic udp server
  .clang-format
  .cz.json
  .github/workflows/build_linux.yml
  .github/workflows/build_windows.yml
  .github/workflows/cmake_build.yml
  .github/workflows/linter.yml
  .github/workflows/sync.yml
  .gitignore
  .pre-commit-config.yaml
  .vscode/c_cpp_properties.json
  CMakeLists.txt
  README.md
  build.sh
  client/src/Client.cpp
  client/src/Client.hpp
  conanfile.txt
  main.cpp
  src/.gitkeep
  src/client/main.cpp
  src/server/Communication.cpp
  src/server/Communication.hpp
  src/server/ConnectionManager.hpp
  src/server/Server.cpp
  src/server/Server.hpp
  src/server/main.cpp
  src/shared/ECS/Components.hpp
  src/shared/ECS/ECS.hpp
  src/shared/MessageQueue/MessageQueue.cpp
  src/shared/MessageQueue/MessageQueue.hpp
Labels: Other

#21 Add windows build instructions to readme
  .clang-format
  README.md
  build.sh
Labels: documentation

#32 [Feature] compile assets in client binary
  CMakeLists.txt
  conanfile.txt
  resources/r-typesheet1.gif
  resources/r-typesheet1.png
  resources/r-typesheet10.gif
  resources/r-typesheet11.gif
  resources/r-typesheet12.gif
  resources/r-typesheet13.gif
  resources/r-typesheet14.gif
  resources/r-typesheet15.gif
  resources/r-typesheet16.gif
  resources/r-typesheet17.gif
  resources/r-typesheet18.gif
  resources/r-typesheet19.gif
  resources/r-typesheet2.gif
  resources/r-typesheet20.gif
  resources/r-typesheet21.gif
  resources/r-typesheet22.gif
  resources/r-typesheet23.gif
  resources/r-typesheet24.gif
  resources/r-typesheet25.gif
  resources/r-typesheet26.gif
  resources/r-typesheet27.gif
  resources/r-typesheet28.gif
  resources/r-typesheet29.gif
  resources/r-typesheet3.gif
  resources/r-typesheet30.gif
  resources/r-typesheet31.gif
  resources/r-typesheet32.gif
  resources/r-typesheet33.gif
  resources/r-typesheet34.gif
  resources/r-typesheet35.gif
  resources/r-typesheet36.gif
  resources/r-typesheet37.gif
  resources/r-typesheet38.gif
  resources/r-typesheet39.gif
  resources/r-typesheet40.gif
  resources/r-typesheet41.gif
  resources/r-typesheet42.gif
  resources/r-typesheet43.gif
  resources/r-typesheet44.gif
  resources/r-typesheet5.gif
  resources/r-typesheet7.gif
  resources/r-typesheet8.gif
  resources/r-typesheet9.gif
  src/client/main.cpp
Labels: Build

#31 [Doc] add Coding Style segment and improve commitizen install guide t…
  CONTRIBUTING.md
Labels: CI / Testing

#30 17 define rfc style protocol
  protocol.txt
Labels: documentation

#36 Develop rebase
  .gitignore
Labels: Other

#34 [Feature] Develop
  .clang-format
  CMakeLists.txt
  CONTRIBUTING.md
  README.md
  build.sh
  conanfile.txt
  resources/r-typesheet1.gif
  resources/r-typesheet1.png
  resources/r-typesheet10.gif
  resources/r-typesheet11.gif
  resources/r-typesheet12.gif
  resources/r-typesheet13.gif
  resources/r-typesheet14.gif
  resources/r-typesheet15.gif
  resources/r-typesheet16.gif
  resources/r-typesheet17.gif
  resources/r-typesheet18.gif
  resources/r-typesheet19.gif
  resources/r-typesheet2.gif
  resources/r-typesheet20.gif
  resources/r-typesheet21.gif
  resources/r-typesheet22.gif
  resources/r-typesheet23.gif
  resources/r-typesheet24.gif
  resources/r-typesheet25.gif
  resources/r-typesheet26.gif
  resources/r-typesheet27.gif
  resources/r-typesheet28.gif
  resources/r-typesheet29.gif
  resources/r-typesheet3.gif
  resources/r-typesheet30.gif
  resources/r-typesheet31.gif
  resources/r-typesheet32.gif
  resources/r-typesheet33.gif
  resources/r-typesheet34.gif
  resources/r-typesheet35.gif
  resources/r-typesheet36.gif
  resources/r-typesheet37.gif
  resources/r-typesheet38.gif
  resources/r-typesheet39.gif
  resources/r-typesheet40.gif
  resources/r-typesheet41.gif
  resources/r-typesheet42.gif
  resources/r-typesheet43.gif
  resources/r-typesheet44.gif
  resources/r-typesheet5.gif
  resources/r-typesheet7.gif
  resources/r-typesheet8.gif
  resources/r-typesheet9.gif
  src/client/main.cpp
  src/server/main.cpp
  src/shared/ECS/CompPool.cpp
  src/shared/ECS/CompPool.hpp
  src/shared/ECS/Component.hpp
  src/shared/ECS/ECS.hpp
  src/shared/ECS/Entity.cpp
  src/shared/ECS/Entity.hpp
  src/shared/ECS/Manager.cpp
  src/shared/ECS/Manager.hpp
Labels: enhancement, CI / Testing, Server, Raylib

#37 [Style] formatted everything
  .clang-format
  CMakeLists.txt
  src/client/main.cpp
  src/server/Communication.cpp
  src/server/Communication.hpp
  src/server/ConnectionManager.hpp
  src/server/Server.cpp
  src/server/Server.hpp
  src/server/main.cpp
  src/shared/ECS/CompPool.cpp
  src/shared/ECS/CompPool.hpp
  src/shared/ECS/ECS.hpp
  src/shared/ECS/Manager.cpp
  src/shared/ECS/Manager.hpp
  src/shared/MessageQueue/MessageQueue.cpp
  src/shared/MessageQueue/MessageQueue.hpp
Labels: Style

#43 33 refacto entity serialization
  .clang-format
  .vscode/c_cpp_properties.json
  CMakeLists.txt
  src/client/sytems/.gitignore
  src/server/main.cpp
  src/server/systems/.gitignore
  src/shared/ECS/Components.hpp
  src/shared/ECS/Components/Armor.hpp
  src/shared/ECS/Components/CollisionEffect.hpp
  src/shared/ECS/Components/Health.hpp
  src/shared/ECS/Components/Position.hpp
  src/shared/ECS/ECS.hpp
  src/shared/ECS/Manager.cpp
  src/shared/ECS/Manager.hpp
  src/shared/MessageQueue/MessageQueue.cpp
  src/shared/MessageQueue/MessageQueue.hpp
  src/shared/systems/serialization.hpp
Labels: Server, Networking

#45 27 add a raylib sprite component
  .gitignore
  CMakeLists.txt
  resources/r-typesheet1.gif
  resources/r-typesheet10.gif
  resources/r-typesheet11.gif
  resources/r-typesheet12.gif
  resources/r-typesheet13.gif
  resources/r-typesheet14.gif
  resources/r-typesheet15.gif
  resources/r-typesheet16.gif
  resources/r-typesheet17.gif
  resources/r-typesheet18.gif
  resources/r-typesheet19.gif
  resources/r-typesheet2.gif
  resources/r-typesheet20.gif
  resources/r-typesheet21.gif
  resources/r-typesheet22.gif
  resources/r-typesheet23.gif
  resources/r-typesheet24.gif
  resources/r-typesheet25.gif
  resources/r-typesheet26.gif
  resources/r-typesheet27.gif
  resources/r-typesheet28.gif
  resources/r-typesheet29.gif
  resources/r-typesheet3.gif
  resources/r-typesheet30.gif
  resources/r-typesheet31.gif
  resources/r-typesheet32.gif
  resources/r-typesheet33.gif
  resources/r-typesheet34.gif
  resources/r-typesheet35.gif
  resources/r-typesheet36.gif
  resources/r-typesheet37.gif
  resources/r-typesheet38.gif
  resources/r-typesheet39.gif
  resources/r-typesheet40.gif
  resources/r-typesheet41.gif
  resources/r-typesheet42.gif
  resources/r-typesheet43.gif
  resources/r-typesheet44.gif
  resources/r-typesheet5.gif
  resources/r-typesheet7.gif
  resources/r-typesheet8.gif
  resources/r-typesheet9.gif
  src/client/main.cpp
  src/client/systems/SpriteSystem.cpp
  src/client/systems/SpriteSystem.hpp
  src/client/systems/Systems.hpp
  src/client/sytems/.gitignore
  src/shared/ECS/Components.cpp
  src/shared/ECS/Components.hpp
  src/shared/ECS/ECS.hpp
  src/shared/ECS/Manager.hpp
  src/shared/systems/ISystem.hpp
  src/shared/systems/Systems.hpp
  src/shared/systems/VelocitySystem.cpp
  src/shared/systems/VelocitySystem.hpp
Labels: Game Engine

#47 [Feature] implement image storage and handling technic
  CMakeLists.txt
  resources/r-typesheet32.png
  src/client/main.cpp
  src/client/systems/SpriteSystem.cpp
  src/client/systems/SpriteSystem.hpp
  src/shared/ECS/Components.hpp
Labels: Game Engine

#50 49 implement UUID system
  CMakeLists.txt
  src/client/main.cpp
  src/client/systems/SpriteSystem.cpp
  src/client/systems/SpriteSystem.hpp
  src/shared/systems/UUID.cpp
  src/shared/systems/UUID.hpp
Labels: enhancement, Game Engine, Networking

#48 40 add root class for client and server
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  CMakeLists.txt
  src/client/Client.cpp
  src/client/Client.hpp
  src/client/ClientGame/ClientGame.cpp
  src/client/ClientGame/ClientGame.hpp
  src/client/main.cpp
  src/server/Communication.cpp
  src/server/Communication.hpp
  src/server/ConnectionManager.hpp
  src/server/Game.cpp
  src/server/Game.hpp
  src/server/Server.cpp
  src/server/Server.hpp
  src/server/main.cpp
  src/shared/MessageQueue/MessageQueue.cpp
  src/shared/MessageQueue/MessageQueue.hpp
  src/shared/Networking/UdpCommunication.cpp
  src/shared/Networking/UdpCommunication.hpp
Labels: Game Engine, Server, Networking, Client

#57 [Feature] various additions
  CMakeLists.txt
  src/client/ClientGame/ClientGame.cpp
  src/client/ClientGame/ClientGame.hpp
  src/client/ClientGame/factories.cpp
  src/client/ClientGame/factories.hpp
  src/client/systems/ArmamentSystem.cpp
  src/client/systems/ArmamentSystem.hpp
  src/client/systems/HealthSystem.cpp
  src/client/systems/HealthSystem.hpp
  src/client/systems/PlayerMovementSystem.hpp
  src/client/systems/SpriteSystem.cpp
  src/client/systems/SpriteSystem.hpp
  src/client/systems/Systems.hpp
  src/shared/ECS/Components.hpp
  src/shared/ECS/ECS.hpp
  src/shared/ECS/Manager.hpp
  src/shared/systems/VelocitySystem.cpp
Labels: Game Engine

#58 [Doc] add comments to UUID
  src/shared/systems/UUID.hpp
Labels: documentation

#68 39 add tcp protocol to protocoltxt
  protocol.txt
Labels: documentation

#69 [Feature] replaced constant loading with on demand loading
  src/client/ClientGame/factories.cpp
  src/client/systems/SpriteSystem.cpp
  src/client/systems/SpriteSystem.hpp
  src/shared/ECS/Components.hpp
Labels: Game Engine

#71 Improvements
  CMakeLists.txt
  src/client/Client.cpp
  src/client/Client.hpp
  src/client/ClientGame/ClientGame.cpp
  src/client/ClientGame/ClientGame.hpp
  src/client/ClientGame/factories.cpp
  src/client/ClientGame/factories.hpp
  src/client/systems/ArmamentSystem.cpp
  src/client/systems/ArmamentSystem.hpp
  src/client/systems/HealthSystem.cpp
  src/client/systems/HealthSystem.hpp
  src/client/systems/PlayerMovementSystem.cpp
  src/client/systems/PlayerMovementSystem.hpp
  src/client/systems/SpriteSystem.cpp
  src/client/systems/SpriteSystem.hpp
  src/server/Game.hpp
  src/shared/ECS/Components.cpp
  src/shared/ECS/Components.hpp
  src/shared/ECS/ECS.hpp
  src/shared/ECS/Manager.cpp
  src/shared/ECS/Manager.hpp
  src/shared/systems/HitboxSystem.cpp
  src/shared/systems/HitboxSystem.hpp
  src/shared/systems/ISystem.hpp
  src/shared/systems/JanitorSystem.cpp
  src/shared/systems/JanitorSystem.hpp
  src/shared/systems/VelocitySystem.cpp
  src/shared/systems/VelocitySystem.hpp
  src/shared/systems/serialization.hpp
Labels: enhancement

#76 75 add tcp command handling client
  .vscode/c_cpp_properties.json
  CMakeLists.txt
  src/client/Client.cpp
  src/client/Client.hpp
  src/client/ClientGame/ClientGame.cpp
  src/client/ClientGame/ClientGame.hpp
  src/client/ClientGame/factories.cpp
  src/client/Protocols/ClientLobbyProtocol.cpp
  src/client/Protocols/ClientLobbyProtocol.hpp
  src/client/Protocols/TcpClient.cpp
  src/client/Protocols/TcpClient.hpp
  src/client/main.cpp
  src/server/Game.cpp
  src/server/Game.hpp
  src/server/Protocols/Connections.hpp
  src/server/Protocols/LobbyProtocol.cpp
  src/server/Protocols/LobbyProtocol.hpp
  src/server/Protocols/TcpServer.cpp
  src/server/Protocols/TcpServer.hpp
  src/server/Server.cpp
  src/server/Server.hpp
  src/shared/MessageQueue/MessageQueue.cpp
  src/shared/MessageQueue/MessageQueue.hpp
  src/shared/Networking/UdpCommunication.cpp
  src/shared/Networking/UdpCommunication.hpp
  src/shared/Utilities/UUID.cpp
  src/shared/Utilities/UUID.hpp
Labels: Networking, Client

#80 78 implement client udp protocol
  CMakeLists.txt
  protocol.txt
  src/client/Protocols/ClientGameProtocol.cpp
  src/client/Protocols/ClientGameProtocol.hpp
  src/server/Protocols/GameProtocol.cpp
  src/server/Protocols/GameProtocol.hpp
  src/shared/ECS/Manager.hpp
  src/shared/Networking/ProtocolUtils.hpp
Labels: Networking, Client

#82 81 plug in logic with protocols
  CMakeLists.txt
  src/client/Client.cpp
  src/client/ClientGame/ClientGame.cpp
  src/client/ClientGame/ClientGame.hpp
  src/client/Protocols/ClientGameProtocol.cpp
  src/client/Protocols/ClientLobbyProtocol.cpp
  src/client/Protocols/ClientLobbyProtocol.hpp
  src/client/Protocols/TcpClient.cpp
  src/client/Systems/HealthSystem.cpp
  src/client/Systems/HealthSystem.hpp
  src/client/Systems/PlayerMovementSystem.cpp
  src/client/Systems/PlayerMovementSystem.hpp
  src/client/Systems/SpriteSystem.cpp
  src/client/Systems/SpriteSystem.hpp
  src/client/systems/SpriteSystem.cpp
  src/server/Game.cpp
  src/server/Game.hpp
  src/server/Protocols/GameProtocol.cpp
  src/server/Protocols/GameProtocol.hpp
  src/server/Protocols/LobbyProtocol.cpp
  src/server/Protocols/LobbyProtocol.hpp
  src/server/Protocols/TcpServer.cpp
  src/server/Server.cpp
  src/server/Server.hpp
  src/server/Systems/ArmamentSystem.cpp
  src/server/Systems/ArmamentSystem.hpp
  src/server/Systems/Factory.cpp
  src/server/Systems/Factory.hpp
  src/shared/ECS/Components.cpp
  src/shared/ECS/Components.hpp
  src/shared/ECS/Manager.cpp
  src/shared/ECS/Manager.hpp
  src/shared/ECS/Serialization.hpp
  src/shared/Networking/ProtocolUtils.hpp
  src/shared/Networking/UdpCommunication.cpp
  src/shared/Networking/UdpCommunication.hpp
  src/shared/Systems/HitboxSystem.cpp
  src/shared/Systems/HitboxSystem.hpp
  src/shared/Systems/ISystem.hpp
  src/shared/Systems/JanitorSystem.cpp
  src/shared/Systems/JanitorSystem.hpp
  src/shared/Systems/VelocitySystem.cpp
  src/shared/Systems/VelocitySystem.hpp
  src/shared/Utilities/Utilities.cpp
  src/shared/Utilities/Utilities.hpp
Labels: bug, Networking, Client

#91 90 add gtest
  .github/workflows/build_linux.yml
  .github/workflows/build_windows.yml
  CMakeLists.txt
  CONTRIBUTING.md
  Makefile
  README.md
  bin/Tests
  build.sh
  src/server/Game.cpp
  test/main.cpp
Labels: CI / Testing, Build

#98 97 test cicd
  .github/workflows/exec_tests.yml
  .gitignore
  bin/Tests
Labels: CI / Testing

#99 92 add music
  CMakeLists.txt
  conanfile.txt
  resources/song0.mp3
  resources/song1.mp3
  src/client/Client.hpp
  src/client/ClientGame/ClientGame.cpp
  src/client/ClientGame/ClientGame.hpp
  src/client/Systems/MusicSystem.cpp
  src/client/Systems/MusicSystem.hpp
  src/client/Systems/SpriteSystem.cpp
  src/client/Systems/Systems.hpp
  src/client/main.cpp
Labels: enhancement, Raylib, Client

#102 96 ecs tests refactor
  .gitignore
  .vscode/launch.json
  CMakeLists.txt
  Makefile
  bin/Tests
  outputCoverage.sh
  src/client/Client.cpp
  src/client/ClientGame/ClientGame.hpp
  src/client/Protocols/ClientGameProtocol.hpp
  src/client/Systems/HealthSystem.cpp
  src/client/Systems/PlayerMovementSystem.cpp
  src/client/Systems/SpriteSystem.cpp
  src/server/Game.cpp
  src/server/Game.hpp
  src/server/Protocols/GameProtocol.cpp
  src/server/Protocols/GameProtocol.hpp
  src/server/Systems/ArmamentSystem.cpp
  src/server/Systems/Factory.cpp
  src/server/Systems/VelocitySystem.cpp
  src/shared/ECS/Components.cpp
  src/shared/ECS/ECS.hpp
  src/shared/ECS/ECSManager.cpp
  src/shared/ECS/ECSManager.hpp
  src/shared/ECS/Manager.cpp
  src/shared/ECS/Serialization.hpp
  src/shared/Systems/HitboxSystem.cpp
  src/shared/Systems/JanitorSystem.cpp
  test/ECS/EcsFixture.cpp
  test/ECS/EcsFixture.hpp
  test/ECS/NewEntity.cpp
Labels: CI / Testing, Game Engine
